# Generated by Django 3.2.8 on 2021-11-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopicApp', '0002_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='url',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
