# Generated by Django 3.2.8 on 2021-10-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BannerApp', '0002_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
