# Generated by Django 3.2.8 on 2021-11-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionApp', '0002_auto_20211031_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='username',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
