# Generated by Django 3.2.8 on 2021-12-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionApp', '0003_transaction_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
