# Generated by Django 3.2.8 on 2021-10-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestsApp', '0002_auto_20211022_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='amount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='payment_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
