# Generated by Django 3.2.8 on 2021-11-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestsApp', '0003_auto_20211031_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='available_at',
            field=models.TextField(null=True),
        ),
    ]
