# Generated by Django 3.2.8 on 2021-11-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestsApp', '0005_auto_20211129_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='available_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
