# Generated by Django 3.2.8 on 2021-11-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestsApp', '0006_alter_requestmodel_available_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='subscriptionId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
