# Generated by Django 3.2.8 on 2022-05-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0004_coursepurchasehistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_url',
            field=models.TextField(null=True),
        ),
    ]
