# Generated by Django 3.2.8 on 2021-10-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_userdetails_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bankaccount_IFSC',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
