# Generated by Django 3.2.8 on 2021-10-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20211024_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bankaccount_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
