# Generated by Django 3.2.8 on 2021-10-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_userdetails_bankaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='commission',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='grade_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
