# Generated by Django 3.2.8 on 2021-10-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_auto_20211028_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_account_holder',
            field=models.BooleanField(default=0),
        ),
    ]
