# Generated by Django 3.2.8 on 2021-11-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_userdetails_referal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='referred_count',
            field=models.IntegerField(default='0', max_length=12),
        ),
    ]
