# Generated by Django 3.2.8 on 2021-11-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_alter_userdetails_referred_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='referred_count',
            field=models.IntegerField(default='0'),
        ),
    ]
