# Generated by Django 3.2.8 on 2021-11-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_alter_userdetails_referred_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='business_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
