# Generated by Django 3.2.8 on 2021-11-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_userdetails_business_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='wallet_credited',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='wallet_withdraw',
            field=models.FloatField(default=0.0),
        ),
    ]
