# Generated by Django 3.2.8 on 2021-10-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotificationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
