# Generated by Django 3.2.8 on 2022-04-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotificationApp', '0003_usernotificationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='external_url',
            field=models.TextField(null=True),
        ),
    ]
