# Generated by Django 3.2.8 on 2021-10-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
        ('SubscriptionApp', '0002_auto_20211028_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ProductApp.product'),
        ),
    ]
