# Generated by Django 3.2.8 on 2021-10-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0003_subscription_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_free_trail',
            field=models.BooleanField(default=False),
        ),
    ]
