# Generated by Django 3.2.8 on 2021-11-25 17:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SubscriptionApp', '0004_subscription_is_free_trail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'product', 'is_free_trail')},
        ),
    ]
