# Generated by Django 3.2.8 on 2021-11-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0005_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
    ]
