# Generated by Django 3.2.8 on 2021-11-27 19:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SubscriptionApp', '0006_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'product', 'is_free_trail')},
        ),
    ]
