# Generated by Django 3.2.8 on 2021-11-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
        ('SubscriptionApp', '0007_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subproduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ProductApp.subproduct'),
        ),
    ]
