# Generated by Django 3.2.8 on 2021-11-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0008_subscription_subproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subproduct',
            new_name='sub_product',
        ),
    ]
