# Generated by Django 3.2.8 on 2021-11-28 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SubscriptionApp', '0009_rename_subproduct_subscription_sub_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'product', 'sub_product', 'is_free_trail')},
        ),
    ]
