# Generated by Django 3.2.8 on 2021-11-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0011_subscription_subscriptionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscriptionId',
        ),
    ]
