# Generated by Django 3.2.8 on 2021-11-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_subscribable',
            field=models.BooleanField(default=False),
        ),
    ]
