# Generated by Django 3.2.8 on 2022-03-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_product_is_subscribable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
