# Generated by Django 3.2.8 on 2021-10-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartnersApp', '0002_auto_20211029_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='available_at',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='phone',
            field=models.CharField(default='14124124', max_length=20),
            preserve_default=False,
        ),
    ]
