# Generated by Django 3.2.8 on 2021-11-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartnersApp', '0003_auto_20211031_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='vip_rank',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
