# Generated by Django 3.2.8 on 2021-11-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartnersApp', '0004_partners_vip_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
