# Generated by Django 3.2.8 on 2021-10-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TopicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(null=True)),
                ('priority', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ManyToManyField(to='TopicApp.Topic')),
            ],
        ),
    ]
