# Generated by Django 3.2.8 on 2021-10-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=255, null=True)),
                ('data_type', models.TextField(choices=[('ARRAY', 'ARRAY'), ('NUMBER', 'NUMBER'), ('TEXT', 'TEXT'), ('BOOLEAN', 'BOOLEAN'), ('DATE', 'DATE'), ('TIME', 'TIME'), ('DATETIME', 'DATETIME')])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
