# Generated by Django 3.2.8 on 2021-10-28 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZalgoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('gender', models.CharField(default='male', max_length=10)),
                ('dob', models.DateField()),
                ('national_id_file', models.FileField(upload_to='')),
                ('national_id', models.CharField(max_length=50)),
                ('pancard_file', models.FileField(upload_to='')),
                ('parncard', models.CharField(max_length=50)),
                ('house_name', models.TextField()),
                ('street_name', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
