# Generated by Django 3.2.8 on 2021-10-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZalgoAccountApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zalgoaccount',
            name='national_id_file',
        ),
        migrations.RemoveField(
            model_name='zalgoaccount',
            name='pancard_file',
        ),
        migrations.AddField(
            model_name='zalgoaccount',
            name='national_id_back',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='zalgoaccount',
            name='national_id_front',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='zalgoaccount',
            name='pancard_back',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='zalgoaccount',
            name='pancard_front',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
