# Generated by Django 3.2.8 on 2021-11-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZalgoAccountApp', '0003_rename_parncard_zalgoaccount_pancard'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalgoaccount',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
