# Generated by Django 3.2.8 on 2021-11-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZalgoAccountApp', '0004_zalgoaccount_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zalgoaccount',
            name='national_id_back',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zalgoaccount',
            name='national_id_front',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zalgoaccount',
            name='pancard_back',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zalgoaccount',
            name='pancard_front',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
